### ISSUE TITLE
Реакция на невидимость

### ISSUE THREAD

**Issue by Todmay** [mark-one-anry/ds01#4]
Если персонаж стал невидимым то слизняк должен терять его из виду

**Comment by Todmay** [comment]
Сейчас это вроде бы работает, но нужно добавить условие что если потерял из виду, то иди к ближайшему кристаллу.

**Comment by mark-one-anry** [comment]
Сейчас слизень, если теряет цель из виду, то идет к последней известной точке и там уже принимает решение, что делать дальше
