### ISSUE TITLE
Слизнь должен быть медленным

### ISSUE THREAD

**Issue by Todmay** [mark-one-anry/ds01#7]
Слизнь должен быть медленным и колдовать замедление на персонажа, скорость слизня изначальная меньше чем у персонажа значительно и лишь немного больше скорости замедленного персонажа

**Comment by Todmay** [comment]
Слизнь игнорирует начальное значение скорости если увидел персонажа

**Comment by mark-one-anry** [comment]
Вынесено в отдельную переменную
